### ISSUE TITLE
👀  Tracking: home page

### ISSUE THREAD

**Issue by arjunr00** [UCLA-Creative-Labs/sunshine#9]
Implement the Home Screen for the new Creative Labs site. 

Reference the [Figma designs](https://www.figma.com/file/dm5sWSjkqeooXCFTDqrpAf/CL-Rebrand-Ideation?node-id=149%3A0).

### Basic Checklist
- [x] static splash screen #3 
- [x] navigation header #1 
- [x] footer #2 
- [x] global style sheet #7 
- [x] about section #6 
- [x] projects section #5 
- [x] fellowship section #4 

### Additional Items:
- [x] time based splash screen #8 
- [x] dynamic splash screen #12 
- [x] mobile responsive #24 
- [x] shore up metadata #23 
- [x] add favicon #34

### Stretch Goals
* weather based splash screen #10

**Comment by arjunr00** [comment]
oops accident^

**Comment by BryanPan342** [comment]
@arjunr00 i think we can close this now?
